### ISSUE TITLE
VS2017 not work

### ISSUE THREAD

**Issue by ahdung** [madskristensen/FileIcons#114]
### Installed product versions
- Visual Studio: [2017 Enterprise]
- This extension: [2.6.172]

### Description
Not work:
![a](https://cloud.githubusercontent.com/assets/12094247/25792813/90d69b08-33fb-11e7-8380-df67eab94339.png)

**Comment by madskristensen** [comment]
Icons cannot be applied to nested files in Solution Explorer. There's nothing this extension can do to fix that
