### ISSUE TITLE
not work in my vs2015

### ISSUE THREAD

**Issue by chenzhikang** [madskristensen/FileIcons#13]
vs2015 enterprise update3
the icons not changed

**Comment by madskristensen** [comment]
what are the file names that doesn't have icons?

**Comment by chenzhikang** [comment]
e.g png and so on

**Comment by chenzhikang** [comment]
![image](https://cloud.githubusercontent.com/assets/9971827/18333062/50bec3cc-759e-11e6-87a6-53583ff64e09.png)

**Comment by chenzhikang** [comment]
i am sure that i install the extension,but i wonder if  there is an on-off to work

**Comment by madskristensen** [comment]
The screenshot you shared shows icons for all the files. It seems to work great. I think you may not know what this extension does. Please check the [readme](https://github.com/madskristensen/FileIcons)

**Comment by chenzhikang** [comment]
i know. thanks
