### ISSUE TITLE
Not working on VS2017 Pro

### ISSUE THREAD

**Issue by miro-poliak** [madskristensen/FileIcons#142]
### Installed product versions
- Visual Studio: [2017 Professional]
- This extension: [2.7.180]

### Description
Not working with VS2017 Pro (Visual Studio 2017)

### Steps to recreate
1. install
2. add file with supported extension to the project

I did try to disable/enable and uninstall/install.

### Current behavior
Icons are not replaced.

### Expected behavior
Icons are replaced.
![image](https://user-images.githubusercontent.com/23461718/32292019-1d750bae-bf15-11e7-83b7-aa1b7cba77ad.png)
![image](https://user-images.githubusercontent.com/23461718/32292038-2f077d7a-bf15-11e7-9268-60c0a21c5f0b.png)

**Comment by madskristensen** [comment]
Fixed
