### ISSUE TITLE
Hey, you missed some old but still relevant grammar files!

### ISSUE THREAD

**Issue by IObsequious** [madskristensen/FileIcons#151]
I am not sure if you want to support these or not, but files with the following extensions:

- Y
- L
- G
- BNF
- EBNF

are just a few of the cannonical input grammar files you provide those lovely compiler generators of old. Thanks a bunch for the ones you and the community have done thus far. Take care!

**Comment by madskristensen** [comment]
Should they have the same icon as .g and .g4 files?

**Comment by IObsequious** [comment]
Sure! Anything is more descriptive than the white box. Thanks for taking the time to write me back.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
