### ISSUE TITLE
Only works the first time after enabling, when using Folder View

### ISSUE THREAD

**Issue by stijnherreman** [madskristensen/FileIcons#153]
### Installed product versions
- Visual Studio: 2017 Community, 15.5.2
- This extension: 2.7.180

### Description
When opening a folder instead of a solution or project, the file icons are only displayed the first time after enabling the extension.

### Steps to recreate
1. Enable the extension.
2. Open a folder. Observe the icons displaying correctly.
3. Restart VS.
4. Open the folder. Observe the icons not displaying at all, not even the default VS icons.
5. Disable the extension and restart VS.
6. Open the folder.  Observe the icons displaying correctly.

### Current behavior
The icons are only displayed once.

### Expected behavior
The icons are always displayed.

**Comment by madskristensen** [comment]
Fixed
