### ISSUE TITLE
.eslintrc extension is deprecated

### ISSUE THREAD

**Issue by tomascassidy** [madskristensen/FileIcons#159]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 2.7

### Description
The configuration file .eslintrc has been deprecated.  It has been replaced with several supported file formats.

https://eslint.org/docs/user-guide/configuring#configuration-file-formats

### Steps to recreate
1. Install this extension
2. Add a .eslintrc.json configuration file

### Current behavior
The ESLint logo is shown only for a .eslintrc file

### Expected behavior
The ESLint logo should be shown for all the supported ESLint configuration file formats.

.eslintrc.js
.eslintrc.yaml
.eslintrc.yml
.eslintrc.json

**Comment by madskristensen** [comment]
Icons cannot be associated with parts of a file path. Only the extension
