### ISSUE TITLE
.xaml.cs code-behind C# icon is the same as for .cs

### ISSUE THREAD

**Issue by mzhukovs** [madskristensen/FileIcons#165]
### Installed product versions
- Visual Studio: 2017 Enterprise/Professional
- This extension: 2.7.201
--

### Description
Special C# icon that has a little arrow or something to indicate it's a code-behind file would be nice for .xaml.cs files

### Steps to recreate
Add a view with a C# code-behind file, e.g. Xamarin Forms .xaml with .xaml.cs code-behind.

### Current behavior
Standard C# icon is displayed

### Expected behavior
Special C# icon that has a little arrow or something to indicate it's a code-behind file would be nice   :)

**Comment by madskristensen** [comment]
That is not possible to do. It has to be implemented by the project system in VS directly.
