### ISSUE TITLE
Missing icon for .prop files

### ISSUE THREAD

**Issue by haldiggs** [madskristensen/FileIcons#170]
They contain build tool settings and user-defined macros, which are saved as project configuration during the development.

In my case I am using one to add compile time constants
`
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<DefineConstants Condition="$([System.Version]::Parse('$(TargetFrameworkVersion.Substring(1))').CompareTo($([System.Version]::Parse('4.5.1')))) &gt;= 0">$(DefineConstants);NET451</DefineConstants>
		<DefineConstants Condition="$([System.Version]::Parse('$(TargetFrameworkVersion.Substring(1))').CompareTo($([System.Version]::Parse('4.5'))))   &gt;= 0">$(DefineConstants);NET45</DefineConstants>
	</PropertyGroup>
</Project>
`

I don't use it often but I saw your notice to report it so here it is.

**Comment by madskristensen** [comment]
The build file is `.props` and not `.prop`
