### ISSUE TITLE
Missing icon for .tst files

### ISSUE THREAD

**Issue by Mervsy** [madskristensen/FileIcons#176]
Hello Mads,

Currently there is no icon for .tst files.  These are used primarily by the "[Typewriter](https://marketplace.visualstudio.com/items?itemName=frhagn.Typewriter)" extension.

**Comment by madskristensen** [comment]
Please open this issue with the TypeWriter extension here https://github.com/frhagn/Typewriter/issues

**Comment by Mervsy** [comment]
On it, thanks Mads!
