### ISSUE TITLE
Missing icon for .view files

### ISSUE THREAD

**Issue by BelarminoVicenzo** [madskristensen/FileIcons#211]
This is how it is presented
![image](https://user-images.githubusercontent.com/20697084/49682879-13560400-fabc-11e8-9988-ebe11e52fb60.png)

**Comment by madskristensen** [comment]
What is a .view file for?

**Comment by BelarminoVicenzo** [comment]
Sorry, it has been almost  2 months.
O already switch the project I was working in, I did a lot of stuff, and I can't remember right now what is .view for.

I think you can close the issue, next time I will write a note to remind me.

Sorry, bro.

**Comment by madskristensen** [comment]
No problem. Thanks for getting back to me so the issue can be closed. Much appreciated
