### ISSUE TITLE
Doesn't work in VS2022

### ISSUE THREAD

**Issue by dehghani-mehdi** [madskristensen/FileIcons#286]
### Installed product versions
- Visual Studio: 2022 Enterprise
- This extension: 2.8.239

### Description
Doesn't work as expected.
![file icon](https://user-images.githubusercontent.com/9152330/141411441-acf89e0e-8cb3-4d5f-b7b7-9b279fa560f3.png)

**Comment by madskristensen** [comment]
How does it not work as expected? The screenshot doesn't seem to show anything wrong with the .css file icon

**Comment by dehghani-mehdi** [comment]
If that is correct icon for CSS, then you are right. I expect better icon tho.

**Comment by dehghani-mehdi** [comment]
Ok, my bad. you are right, I think the icon should not be black & white tho.
