### ISSUE TITLE
file associations with Visual Studio

### ISSUE THREAD

**Issue by Hypsellis** [madskristensen/FileIcons#29]
FileIcons add a lot of icons support for many files in the solution explorer, but it doesn't add any file associations with Visual Studio and new icons on the windows explorer. It would be awesome if this extension added all the missing file associations in HKEY_CLASSES_ROOT, because add them manually is just fucking long and annoying. Anyway this extension is awesome, thanks a lot for it. :p

**Comment by madskristensen** [comment]
That would be cool, but most of the images I associate with the file extensions are embedded in VS, so I can't add them to the registry

**Comment by Hypsellis** [comment]
What do you mean ? I'm not sure to understand.

**Comment by madskristensen** [comment]
I mean that most images in this extension are not on disk. They are XAML files embedded in Visual Studio. Because of that I can't associate them with the Windows file system in the registry as you suggested

**Comment by Hypsellis** [comment]
Oh I see, I didn't know it was possible to make icons in XAML, why not use ico files ?

**Comment by madskristensen** [comment]
All icons shipped in VS is in XAML so they are fully vectorized and works in all DPI settings and resolutions
