### ISSUE TITLE
Missing icon for .target files

### ISSUE THREAD

**Issue by douglasshelby** [madskristensen/FileIcons#38]
Optionally, please give more details as to what the file type is used for.

**Comment by madskristensen** [comment]
Is this for MSBuild? Did you perhaps mean `.targets` with a `s` at the end? That one is already included

**Comment by douglasshelby** [comment]
Thanks Mads.  You're right. 

Doug Shelby
______________________
douglas.shelby@gmail.com
630.430.8477
