### ISSUE TITLE
Missing icon for .dxview files

### ISSUE THREAD

**Issue by NikolaStefanovski** [madskristensen/FileIcons#39]
A .dxview file is part of the DevExpress framework. It's a file that has a design for the view (ex. a tab view on a tablet) for the presentation layer. It's similar to a view in WebForms ( .aspx). WebForm has an .aspx for the design and a .cs for the code, DevExtreme has .dxview for the design and .js for the code.

**Comment by madskristensen** [comment]
Fixed
