### ISSUE TITLE
Missing icon for .t4 files

### ISSUE THREAD

**Issue by bilalarshad** [madskristensen/FileIcons#41]
Optionally, please give more details as to what the file type is used for.

**Comment by madskristensen** [comment]
Do you mean .tt files (for T4 templates) by chance? The .t4 file extension doesn't do anything does it?

**Comment by bilalarshad** [comment]
I am using T4 templates to provide scaffolding for generating repository modules based upon a Model.

**Comment by madskristensen** [comment]
right, but isn't the file called .tt and not .t4?
