### ISSUE TITLE
Can this be used to adjust existing icons?

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/FileIcons#57]
I know this is outside the scope of this plugin, but I was wondering if this could be modified to use a different set of icons for those that already exist? My intent is to use the [seti-ui](https://github.com/jesseweed/seti-ui) icons similar to the [seti-icons](https://marketplace.visualstudio.com/items?itemName=qinjia.seti-icons) vs code plugin.

**Comment by madskristensen** [comment]
No, unfortunately not. I think the only way to do that is to fork this extension and replace the icons with the seti ones
