### ISSUE TITLE
Icon for gulpfile.js

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/FileIcons#61]
Would be great to have support for `gulpfile.js`.

![](https://avatars0.githubusercontent.com/u/6200624)

**Comment by madskristensen** [comment]
That would be awesome and I so wish this was supported by VS, but unfortunately I can only add icons per file extension and not individual file names. Would be so cool though

**Comment by drewnoakes** [comment]
That is a shame, but not to worry. Thanks for the great extensions!
