### ISSUE TITLE
After Extension Installation does not seem to be working.

### ISSUE THREAD

**Issue by frobozz67** [madskristensen/FileIcons#62]
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3

File Icons   2.3
Adds icons for files that are not recognized by Solution Explorer

### Description
Installed Extension (twice) but not showing icon for .gitignore nor when I right click on the file
do I see menu item "Report missing icon for .missing files..."

![image](https://cloud.githubusercontent.com/assets/13202495/21896788/893c9c72-d8b5-11e6-8e8a-4256939d6d42.png)

![image](https://cloud.githubusercontent.com/assets/13202495/21896868/ccba6574-d8b5-11e6-9ea5-d893e65a3f5b.png)

**Comment by madskristensen** [comment]
VS only shows icons for files that are included in the project. Looks like the README.md file got the right icon since it's included in the project. Can you verify?

**Comment by frobozz67** [comment]
That was it, the file was not included in the Project. After I included the file in the Project the correct icon appeared.

Thanks
