### ISSUE TITLE
Missing icon for .babylon files

### ISSUE THREAD

**Issue by ChrisOMetz** [madskristensen/FileIcons#63]
Optionally, please give more details as to what the file type is used for.

**Comment by madskristensen** [comment]
What is a .babylon file? Is it this? http://www.redpin.eu/

**Comment by ChrisOMetz** [comment]
Nope.. It's babylonjs.com . But I'm not sure if it is really necessary to add all possible file extensions for every library or add on... You decide!

**Comment by madskristensen** [comment]
It looks like it is just JavaScript with a `.js` extension. I didn't see any mention of `.babylon` files. Is a .babylon file just a JavaScript file with a different file extension and is it commonly used?

**Comment by ChrisOMetz** [comment]
It is a json formatted definition files. An example can be found at https://github.com/BabylonJS/Babylon.js/tree/master/assets/meshes . But this is more a convention while using babylon.js. Any other file extension would also work perfectly.
I don' think this should be added with a specific file type icon. As it is to special.
