### ISSUE TITLE
Ability to specify that FileIcons should not add file icon for a specific file extension

### ISSUE THREAD

**Issue by StephRagazzi** [madskristensen/FileIcons#88]
### Installed product versions
- Visual Studio 2017 Professional
- This extension: 2.6.172

### Description
I have an extension installed called Specflow. The extension for that type of file is .feature.
I would like to keep the Specflow original extension icon in visual studio.
FileIcons override the original icon

### Current behavior
The FileIcons extension override my original extension icon

### Expected behavior
I would like to be able to specify that a file extension should not be overriden by FileIcons extension

**Comment by kulemeevag** [comment]
I join the wish

**Comment by madskristensen** [comment]
I wish it was possible, but Visual Studio doesn't allow for that
