### ISSUE TITLE
Folder Support

### ISSUE THREAD

**Issue by KhmerBoi1** [madskristensen/FileIcons#89]
### Installed product versions
- Visual Studio: 2015 Enterprise / 2017  Community
- This extension: 2.6.172

### Description
Request to have your extension support folders as well just like vscode-icons

**Comment by madskristensen** [comment]
I'm not sure that is supported in VS, but I can try to find out

**Comment by madskristensen** [comment]
This is not possible unless you roll your own project system/type which is not a solution to that makes sense for this. Unfortunately.

**Comment by nithinbandaru1** [comment]
Hmm that's bad.
