### ISSUE TITLE
Missing icon for .psm1 files

### ISSUE THREAD

**Issue by IObsequious** [madskristensen/FileIcons#9]
As you probably well know, this is the extension for a powershell module script file. It appears as that famous "Square Nothing" in solution explorer, which may be telling, because I find myself becoming angry with PowerShell quite often...

**Comment by madskristensen** [comment]
This was added in the latest release. Can you please verify that it works if you install the latest version?

**Comment by IObsequious** [comment]
Confirmed. Thank you very much!
