### ISSUE TITLE
Missing icon for .tsconfig files

### ISSUE THREAD

**Issue by Jkaveri** [madskristensen/FileIcons#94]
Optionally, please give more details as to what the file type is used for.

**Comment by madskristensen** [comment]
What is this for? Did you mean to use tsconfig.json?

**Comment by Jkaveri** [comment]
Yes

**Comment by madskristensen** [comment]
So this can be closed then?

**Comment by Jkaveri** [comment]
Can we use a separate icon for specific config file? 
e.g. package.json, tsconfig.json

**Comment by madskristensen** [comment]
Unfortunately not. VS only allows icons to be associated with file extensions, not file names
